services:
  homeserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JAVA_TOOL_OPTIONS=-Dconfig.file=/app/config/application.conf
    volumes:
      - ./server_data:/app/data
      - ./config/application.conf:/app/config/application.conf
      - /var/run/docker.sock:/var/run/docker.sock
