name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master", "development" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/sonar-analysis.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/sonar-analysis.yml'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build in Docker
        # We build the image using the custom Dockerfile. 
        # The build command runs ./gradlew :server:build inside the build process.
        # If it fails, the docker build command will fail, failing the CI job.
        run: docker build -f .github/docker/ci.Dockerfile .

      - name: Send Build status
        uses: yanzay/notify-telegram@1025564e15f68b2fcddeba37b5bfaf4033c79448 # v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }} # do not modify this line
